name: NISAR_Disturbance
channels:
  - conda-forge
dependencies:
  - asf_search 
  - boto3
  - datashader
  - earthaccess
  - fpdf
  - gdal
  - geopandas
  - geoviews
  - h5py
  - holoviews
  - hvplot
  - ipykernel
  - ipywidgets
  - jupyter
  - matplotlib
  - nb_conda_kernels  
  - notebook
  - numpy
  - pandas
  - pre-commit 
  - python
  - pyproj
  - rasterio
  - rioxarray
  - scikit-learn
  - scipy
  - tqdm